Allow custom stages in aggregation pipeline
MorphiaOrg/morphia pull request #2126
Opened 2022-10-29 12:45 UTC by richarddd

This will let users add more stages

2022-11-03 01:54 UTC, evanchooly requested changes
Thanks for the PR.  I'd been weighing a similar change.  Note that 2.3, when it comes out soon, should have all the stages implemented but I know sometimes a Morphia release can lag behind the release of new pipeline stages in the server so this will be a nice stopgap for the industrious until Morphia can catch up.

There's a little clean up to do here and there but once that's done we can get this merged.

2022-11-03 01:54 UTC, evanchooly commented on core/src/main/java/dev/morphia/aggregation/Aggregation.java
> +import dev.morphia.aggregation.stages.*;
* imports break checkstyle so you'll want to clean that up.  The code formatter that runs as part of the maven build *should* clean that up but if not, you'll need to manually expand those.

2022-11-03 01:54 UTC, evanchooly commented on core/src/main/java/dev/morphia/aggregation/Aggregation.java
> +    List<Stage> getStates();
This method should not be on the public interface.  I understand *why* it's there.  You want to test.  But you should downcast in your test.  There's no reason for user code to call this as it's an internal implementation detail.

2022-11-03 01:54 UTC, evanchooly commented on core/src/main/java/dev/morphia/aggregation/AggregationImpl.java
> +        return addStage(bucket);
These changes are a little noisy in this PR.  But i get it.  I'd been meaning to do this but it just never bothered me enough to clean it up.

2022-11-03 01:54 UTC, evanchooly commented on core/src/main/java/dev/morphia/aggregation/AggregationImpl.java
> +    public List<Stage> getStates() {
typo in the method name

2022-11-14 03:57 UTC, evanchooly commented
@richarddd any updates?

2022-11-15 10:42 UTC, richarddd commented
> @richarddd any updates?

Done!

2022-11-17 18:23 UTC, evanchooly commented
@richarddd do you understand what needs to be fixed on the PR?

2022-11-18 10:30 UTC, richarddd commented
> @richarddd do you understand what needs to be fixed on the PR?

Not quite? I did change what you've requested and updated it again

2022-11-18 15:57 UTC, evanchooly commented
There are some style checks failing.  You can see in the message at the end how to fix it.  you can run those checks locally with `mvn -Dcode-audits` and you'll see the error, and fix, when it's done.

2022-11-27 04:42 UTC, evanchooly commented
i applied the audit fixes for you but I need you to rebase your PR.  It looks like you have older commits in your log.

2022-11-28 00:57 UTC, evanchooly commented
manually merged

2022-11-28 00:57 UTC, closed without merging